--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -477,3 +477,4 @@
 obj-$(CONFIG_HTC_RPM_CMD) += rpm_htc_cmd.o
 obj-$(CONFIG_HTC_MONITOR) += htc_monitor.o
 obj-$(CONFIG_MSM_CPUFREQ_LIMITER) += cpufreq_limit.o
+obj-$(CONFIG_LCD_KCAL) += htc_kcal_ctrl.o
